-- Community Support System Database Schema
-- PostgreSQL DDL for ERD Diagram

-- 1. LOCATIONS Table (Rwandan Administrative Hierarchy)
CREATE TABLE locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cell VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL,
    province VARCHAR(255) NOT NULL,
    province_code VARCHAR(255) UNIQUE,
    sector VARCHAR(255) NOT NULL,
    village VARCHAR(255) NOT NULL,
    PRIMARY KEY (location_id)
);

-- 2. USERS Table (Citizens and Volunteers)
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    location_id BIGINT,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('CITIZEN','VOLUNTEER')),
    PRIMARY KEY (user_id)
);

-- 3. SKILLS Table (Available Skills)
CREATE TABLE skills (
    skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(500),
    skill_name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (skill_id)
);

-- 4. REQUESTS Table (Help Requests)
CREATE TABLE requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    citizen_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    description VARCHAR(1000) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING','ACCEPTED','COMPLETED','CANCELLED')),
    title VARCHAR(255) NOT NULL,
    PRIMARY KEY (request_id)
);

-- 5. ASSIGNMENTS Table (Volunteer Assignments)
CREATE TABLE assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    accepted_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),
    request_id BIGINT NOT NULL,
    volunteer_id BIGINT NOT NULL,
    PRIMARY KEY (assignment_id)
);

-- 6. NOTIFICATIONS Table (User Notifications)
CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL,
    message VARCHAR(500) NOT NULL,
    PRIMARY KEY (notification_id)
);

-- 7. USER_SKILLS Table (Many-to-Many Junction Table)
CREATE TABLE user_skills (
    skill_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (skill_id, user_id)
);

-- FOREIGN KEY CONSTRAINTS (Relationships)

-- Users → Locations (Many-to-One)
ALTER TABLE users 
ADD CONSTRAINT FK_users_location 
FOREIGN KEY (location_id) REFERENCES locations(location_id);

-- Requests → Users (Many-to-One: Citizen)
ALTER TABLE requests 
ADD CONSTRAINT FK_requests_citizen 
FOREIGN KEY (citizen_id) REFERENCES users(user_id);

-- Assignments → Requests (Many-to-One)
ALTER TABLE assignments 
ADD CONSTRAINT FK_assignments_request 
FOREIGN KEY (request_id) REFERENCES requests(request_id);

-- Assignments → Users (Many-to-One: Volunteer)
ALTER TABLE assignments 
ADD CONSTRAINT FK_assignments_volunteer 
FOREIGN KEY (volunteer_id) REFERENCES users(user_id);

-- Notifications → Users (Many-to-One)
ALTER TABLE notifications 
ADD CONSTRAINT FK_notifications_user 
FOREIGN KEY (user_id) REFERENCES users(user_id);

-- User_Skills → Skills (Many-to-Many)
ALTER TABLE user_skills 
ADD CONSTRAINT FK_user_skills_skill 
FOREIGN KEY (skill_id) REFERENCES skills(skill_id);

-- User_Skills → Users (Many-to-Many)
ALTER TABLE user_skills 
ADD CONSTRAINT FK_user_skills_user 
FOREIGN KEY (user_id) REFERENCES users(user_id);

-- INDEXES for Performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_location ON users(location_id);
CREATE INDEX idx_requests_status ON requests(status);
CREATE INDEX idx_requests_citizen ON requests(citizen_id);
CREATE INDEX idx_assignments_volunteer ON assignments(volunteer_id);
CREATE INDEX idx_assignments_request ON assignments(request_id);
CREATE INDEX idx_notifications_user ON notifications(user_id);
CREATE INDEX idx_locations_province_code ON locations(province_code);

-- SAMPLE DATA for Testing (Complete Rwandan Administrative Structure)
INSERT INTO locations (province, district, sector, cell, village, province_code) VALUES
-- Kigali City (3 Districts)
('Kigali City', 'Gasabo', 'Remera', 'Gisozi', 'Ubumwe', 'KG'),
('Kigali City', 'Kicukiro', 'Niboye', 'Kagarama', 'Nyarugunga', 'KG'),
('Kigali City', 'Nyarugenge', 'Nyarugenge', 'Rwezamenyo', 'Biryogo', 'KG'),

-- Eastern Province (7 Districts)
('Eastern Province', 'Nyagatare', 'Nyagatare', 'Rukomo', 'Karama', 'EP'),
('Eastern Province', 'Gatsibo', 'Gatsibo', 'Gitoki', 'Kageyo', 'EP'),
('Eastern Province', 'Bugesera', 'Ntarama', 'Zaza', 'Mayange', 'EP'),
('Eastern Province', 'Kayonza', 'Kayonza', 'Mukarange', 'Murama', 'EP'),
('Eastern Province', 'Ngoma', 'Sake', 'Mugesera', 'Kibungo', 'EP'),
('Eastern Province', 'Kirehe', 'Kirehe', 'Nasho', 'Mahama', 'EP'),
('Eastern Province', 'Rwamagana', 'Muhazi', 'Gahengeri', 'Kabare', 'EP'),

-- Western Province (7 Districts)
('Western Province', 'Rusizi', 'Kamembe', 'Muganza', 'Nkanka', 'WP'),
('Western Province', 'Rubavu', 'Gisenyi', 'Nyundo', 'Cyanzarwe', 'WP'),
('Western Province', 'Nyamasheke', 'Kagano', 'Kanjongo', 'Nyabitekeri', 'WP'),
('Western Province', 'Ngororero', 'Bwira', 'Matyazo', 'Gatumba', 'WP'),
('Western Province', 'Karongi', 'Bwishyura', 'Mutuntu', 'Bwishyura', 'WP'),
('Western Province', 'Rutsiro', 'Kigeyo', 'Ruhango', 'Mushonyi', 'WP'),
('Western Province', 'Nyabihu', 'Mukamira', 'Jenda', 'Shyira', 'WP'),

-- Southern Province (8 Districts)
('Southern Province', 'Kamonyi', 'Kamonyi', 'Rugalika', 'Nyamiyaga', 'SP'),
('Southern Province', 'Nyamagabe', 'Gasaka', 'Mushubi', 'Tare', 'SP'),
('Southern Province', 'Huye', 'Ngoma', 'Matyazo', 'Rwaniro', 'SP'),
('Southern Province', 'Nyanza', 'Busasamana', 'Rwabicuma', 'Cyabakamyi', 'SP'),
('Southern Province', 'Gisagara', 'Save', 'Kigembe', 'Mamba', 'SP'),
('Southern Province', 'Ruhango', 'Ruhango', 'Kabagari', 'Muhanga', 'SP'),
('Southern Province', 'Muhanga', 'Muhanga', 'Cyeza', 'Shyogwe', 'SP'),
('Southern Province', 'Nyaruguru', 'Nyamagabe', 'Kibeho', 'Cyanika', 'SP'),

-- Northern Province (5 Districts)
('Northern Province', 'Gicumbi', 'Byumba', 'Bungwe', 'Cyumba', 'NP'),
('Northern Province', 'Gakenke', 'Gakenke', 'Janja', 'Kivuruga', 'NP'),
('Northern Province', 'Burera', 'Cyeru', 'Butaro', 'Nemba', 'NP'),
('Northern Province', 'Rulindo', 'Base', 'Burega', 'Cyinzuzi', 'NP'),
('Northern Province', 'Musanze', 'Muhoza', 'Nyakinama', 'Cyuve', 'NP');

INSERT INTO skills (skill_name, description) VALUES
('Programming', 'Software development and coding'),
('Tutoring', 'Academic tutoring and teaching'),
('Delivery', 'Package and grocery delivery services'),
('Tech Support', 'Computer and technology assistance'),
('Cooking', 'Meal preparation and cooking assistance'),
('Healthcare', 'Medical assistance and health support'),
('Construction', 'Building and repair services'),
('Transportation', 'Vehicle and transport services'),
('Agriculture', 'Farming and agricultural support'),
('Education', 'Teaching and educational support');